version: '2'
services:
  redis-cluster:
    environment:
      IP: ${REDIS_CLUSTER_IP}
    build:
      context: .
      args:
        redis_version: '6.2.1'
    hostname: server
    ports:
      - '7000-7050:7000-7050'
      - '5000-5010:5000-5010'
